# This is a basic workflow to help you get started with Actions

name: Autograding

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "feedback", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Student Repo
        uses: actions/checkout@v3
        timeout-minutes: 2
        with:
          path: student_code

      # Runs a single command using the runners shell
      - name: Master Repo
        uses: actions/checkout@v3
        timeout-minutes: 2
        with:
          token: ${{secrets.F22_3155_PAT}}
          repository: csci3155/pppl-labdev
          path: master_code

      - name: Prep Grading
        timeout-minutes: 2
        run: ./gradepreplab6.sh .
        working-directory: ./master_code

      # Grade the current
      - name: Grade current 
        timeout-minutes: 2
        run: ./gradelab6.sh ../student_code . ../ 2>&1 | tee ../grading.log
        working-directory: ./master_code

      # Display the score
      - name: Display Score
        run: tail -n 1 grading.log
        

          
