# This is a basic workflow to help you get started with Actions
name: sbt compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "feedback", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Student Repo
        uses: actions/checkout@v3
        timeout-minutes: 2
        with:
          path: student_code

      - name: Setup JDK
        uses: actions/setup-java@v3
        timeout-minutes: 2
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Run sbt compile
        timeout-minutes: 2
        working-directory: ./student_code
        run: sbt compile

